### ISSUE TITLE
.NET 5 and Ubuntu compatibility

### ISSUE THREAD

**Issue by Dave3991** [henon/Python.Included#23]
Enviroment: Ubuntu 20.04

Error:
```Unhandled exception. System.DllNotFoundException: Unable to load shared library 'python3.7m' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libpython3.7m: cannot open shared object file: No such file or directory
   at Python.Runtime.Runtime.Py_IsInitialized()
   at Python.Runtime.Runtime.Initialize(Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize()
   at PythonExecutor.Program.Main(String[] args) in /home/david/Documents/personal/gitlab/inventory-management/InventoryManagement/app/PythonExecutor/Program.cs:line 13

Process finished with exit code 134.
```

Steps to reproduce:
run this code:
```
using System;
using Python.Runtime;

namespace PythonExecutor
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            Environment.SetEnvironmentVariable("LD_DEBUG","true");
            PythonEngine.Initialize();
            dynamic sys=PythonEngine.ImportModule("sys");
            Console.WriteLine("Python version: " + sys.version);
        }
    }
}
```

I think it's because it's not multiplatform ?

**Comment by henon** [comment]
check the last comment of #1 maybe that is the problem for you too?

**Comment by Dave3991** [comment]
I would like to try it, but I don't know how to remove "PYTHON_WITH_PYMALLOC" during build of pythonnet :(

**Comment by henon** [comment]
ok, let me update the nuget quickly. hang on

**Comment by henon** [comment]
I removed pymalloc from linux and mac versions of pythonnet for py3.8. check out the pythonnet nuget v2.5.1.1

**Comment by Dave3991** [comment]
@henon I installed library you metioned and I'm getting different error
```
Hello World!
Unhandled exception. System.MissingMethodException: Method not found: 'System.Reflection.Emit.AssemblyBuilder System.AppDomain.DefineDynamicAssembly(System.Reflection.AssemblyName, System.Reflection.Emit.AssemblyBuilderAccess)'.
   at Python.Runtime.CodeGenerator..ctor()
   at Python.Runtime.DelegateManager..ctor()
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize()
   at PythonExecutor.Program.Main(String[] args) in /home/david/Documents/personal/gitlab/inventory-management/InventoryManagement/app/PythonExecutor/Program.cs:line 26

Process finished with exit code 134.

```

**Comment by henon** [comment]
With that I can't help you further. Please make a reproduction of the error without involvement of Python.Included so the pythonnet guys are not suspecting me of having done something wrong on my end and create an issue on their repo.

**Comment by Dave3991** [comment]
I don't know what happend, but I try several other pythonnet nugets then I install back pythonnet_netstandard_py38_linux version 2.5.1.1 and this code starts to work

```
namespace PythonExecutor
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            using (Py.GIL())
            {
                dynamic sys=PythonEngine.ImportModule("sys");
                Console.WriteLine("Python version: " + sys.version);
            }
        }
    }
}
```

@henon big thank you for your patience and willingness :+1:  you are good guy
