### ISSUE TITLE
Crashes under Pandas memory-intensive load

### ISSUE THREAD

**Issue by mihakralj** [henon/Python.Included#38]
Pandas and Pandas-TA, this is what I get when running couple more intense calculations:
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at Python.Runtime.Runtime.PyObject_HasAttrString(IntPtr, System.String)
--------------------------------
   at Python.Runtime.Exceptions.Shutdown()
   at Python.Runtime.Runtime.Shutdown()
   at Python.Runtime.PythonEngine.ExecuteShutdownHandlers()
   at Python.Runtime.PythonEngine.Shutdown()
   at Validation.PandasTA.Finalize()
```

Running small/simple Python scripts works ok.

**Comment by henon** [comment]
Hi, Python.Included only provides a convenient installation mechanism of Pythonnet. Your issue is way beyond my knowledge of the internals of Pythonnet. Looks to me like a pointer error which is always extremely hard to debug. Sorry that I can't help you with this.
